data_transformation:
  target: dev
  outputs:
    dev:
      type: "{{ env_var('DBT_DEV_TYPE', 'postgres') }}"
      host: "{{ env_var('DBT_DEV_HOST') }}"
      user: "{{ env_var('DBT_DEV_USER') }}"
      password: "{{ env_var('DBT_DEV_PASSWORD') }}"
      port: "{{ env_var('DBT_DEV_PORT', '5432') | int }}"
      dbname: "{{ env_var('DBT_DEV_DBNAME') }}"
      schema: "{{ env_var('DBT_DEV_SCHEMA') }}"
      threads: "{{ env_var('DBT_DEV_THREADS', '4') | int }}"
      keepalives_idle: 0
